### ISSUE TITLE
Error on aofl init command on Windows

### ISSUE THREAD

**Issue by raybarrera** [AgeOfLearning/aofl#11]
**Describe the bug**
When attempting to init a new project using the aofl cli tools, I get an error in events.js

**To Reproduce**
1. Install aofl/cli using the npm command (npm i -g @aofl/cli)
2. [npx] aofl init path/to/myproject
3. observe the following error:
```
running... npm i

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Desktop (please complete the following information):**
 - OS: Windows 10, Command Prompt or Cmder
 - npm version: 6.5.0
 - node version: v10.14.2

**Comment by arianics** [comment]
fixed in  [v1.4.0](https://github.com/AgeOfLearning/aofl/releases/tag/v1.4.0) 5f30e1b
